# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=5)),
                ('price', models.CharField(max_length=8)),
                ('image', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('check_in_date', models.CharField(blank=True, max_length=20, null=True)),
                ('check_out_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'hotels',
            },
        ),
    ]
